Phuc create Pull Request
sonnguyen112/rookie_hackathon_contest_platform pull request #10
Opened 2024-01-04 14:05 UTC by phamngocphuc

2024-01-04 14:24 UTC, phamngocphuc commented
Chức năng 'Search Quiz' và 'Join Quiz'

2024-01-04 14:48 UTC, sonnguyen112 requested changes
Em xin đóng góp các ý kiến:
        + Cần có logic kiểm tra thời gian làm bài có hợp lệ ko(thời gian hiện tại phải nằm trong khoảng thời gian  bắt đầu và thời gian kết thúc
        + Cần có logic kiểm tra xem người dùng đã làm bài Quiz này hay chưa, nếu làm rồi thì ko đc làm nữa.

2024-01-04 14:57 UTC, phamngocphuc commented
Này đang là chức năng tìm kiếm bài quiz theo thời gian mà Sơn. Nghĩa là tìm kiếm những phải Quiz nằm trong khoảng thời gian tìm kiếm mà nhỉ. Sao phải cần kiểm tra người dùng đã làm bài hay chưa á Sơn

2024-01-04 15:00 UTC, sonnguyen112 commented
Dạ trong chức năng làm tham gia bài Quiz ấy ạ, mà lúc náy e nhìn ko kĩ nên ko thấy đoạn a check thời gian, em nhìn kĩ lại thì em thấy rồi, còn cái kiểm tra ngươì dùng đã làm bài hay chưa là để đảm bảo chỉ được làm bài 1 lần thôi

2024-01-04 15:02 UTC, phamngocphuc commented
Ụa chứ ko phải chức năng Search này dành cho giao diện Admin à em :D

2024-01-04 15:04 UTC, sonnguyen112 commented
Dạ em chưa có xem cái chức năng Seach, em mới xem cái chức năng Join Quiz thui thì em thấy cần bổ sung 2 cái đó, 1 là phải nằm trog khoảng tg bắt đầu và kết thúc thì mới làm quiz đc, 2 là nếu làm rồi thì ko đc làm nữa

2024-01-04 15:06 UTC, phamngocphuc commented
À a tưởng em nói chức năng Search. Okee anh hiểu rồi để a check lại logic Join làm Quiz :D

2024-01-06 15:16 UTC, sonnguyen112 approved these changes

2024-01-06 15:16 UTC, merged